[package]
name = "openapi-path-filter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.2"
serde_json = "1.0.138"
matchit = "0.8.6"
serde = { version = "1.0.217", features = ["derive"] }